// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	models "github.com/duvansh91/xmen/internal/human/models"
	mock "github.com/stretchr/testify/mock"
)

// HumanRepository is an autogenerated mock type for the HumanRepository type
type HumanRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *HumanRepository) FindAll() ([]*models.Human, error) {
	ret := _m.Called()

	var r0 []*models.Human
	if rf, ok := ret.Get(0).(func() []*models.Human); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Human)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: human
func (_m *HumanRepository) Save(human *models.Human) error {
	ret := _m.Called(human)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Human) error); ok {
		r0 = rf(human)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
