version: "3.9"

services:
  xmen:
    build:
      context: ./
      dockerfile: Dockerfile
    image: xmen
    container_name: xmen
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - MONGO_DATABASE=xmen
      - SERVER_PORT=8080

  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb_data:/etc/mongo"
