// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	models "github.com/duvansh91/xmen/internal/human/models"
	mock "github.com/stretchr/testify/mock"
)

// GetStats is an autogenerated mock type for the GetStats type
type GetStats struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *GetStats) Get() (*models.Stats, error) {
	ret := _m.Called()

	var r0 *models.Stats
	if rf, ok := ret.Get(0).(func() *models.Stats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Stats)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
